# Generated by Django 3.1.7 on 2021-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
