# Generated by Django 3.1.7 on 2021-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210326_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='position',
            field=models.CharField(choices=[('FWD', 'Forward'), ('Mid', 'Midfielder'), ('Def', 'Defender'), ('Gk', 'Goalkeeper')], default='Not Assigned', max_length=10),
        ),
    ]
