# Generated by Django 3.1.7 on 2021-03-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playerinfo_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assists', models.IntegerField(blank=True, default=0, null=True)),
                ('total_passes', models.IntegerField(blank=True, default=0, null=True)),
                ('passes_per_match', models.IntegerField(blank=True, default=0, null=True)),
                ('chances_created', models.IntegerField(blank=True, default=0, null=True)),
                ('crosses', models.IntegerField(blank=True, default=0, null=True)),
                ('cross_accuracy', models.IntegerField(blank=True, default=0, null=True)),
                ('through_balls', models.IntegerField(blank=True, default=0, null=True)),
                ('long_balls', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('red_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('fouls', models.IntegerField(blank=True, default=0, null=True)),
                ('offsides', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DefensiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_sheets', models.IntegerField(blank=True, default=0, null=True)),
                ('goals_conceded', models.IntegerField(blank=True, default=0, null=True)),
                ('tackles', models.IntegerField(blank=True, default=0, null=True)),
                ('tacles_success_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('blocked_shots', models.IntegerField(blank=True, default=0, null=True)),
                ('interceptions', models.IntegerField(blank=True, default=0, null=True)),
                ('recoveries', models.IntegerField(blank=True, default=0, null=True)),
                ('duels_won', models.IntegerField(blank=True, default=0, null=True)),
                ('dues_lost', models.IntegerField(blank=True, default=0, null=True)),
                ('successful_50_50', models.IntegerField(blank=True, default=0, null=True)),
                ('aerial_battles_won', models.IntegerField(blank=True, default=0, null=True)),
                ('aerial_battles_lost', models.IntegerField(blank=True, default=0, null=True)),
                ('own_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AttackingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, default=0, null=True)),
                ('headers', models.IntegerField(blank=True, default=0, null=True)),
                ('right_foot_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('left_foot_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('penalties', models.IntegerField(blank=True, default=0, null=True)),
                ('freekicks', models.IntegerField(blank=True, default=0, null=True)),
                ('shots', models.IntegerField(blank=True, default=0, null=True)),
                ('shots_on_target', models.IntegerField(blank=True, default=0, null=True)),
                ('accuracy', models.IntegerField(blank=True, default=0, null=True)),
                ('hit_woodwork', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerinfo')),
            ],
        ),
    ]
