# Generated by Django 3.1.7 on 2021-03-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attackingstats_defensivestats_disciplinarystats_teamplaystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='apps',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='jersey_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
