# Generated by Django 3.1.7 on 2021-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210329_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackingstats',
            name='accuracy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
