# Generated by Django 3.1.7 on 2021-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210329_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='clean_sheets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
