# Generated by Django 3.1.7 on 2021-03-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playerinfo_clean_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='goals',
        ),
        migrations.CreateModel(
            name='GoalkeepingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_sheets', models.IntegerField(blank=True, default=0, null=True)),
                ('saves', models.IntegerField(blank=True, default=0, null=True)),
                ('penalties_saved', models.IntegerField(blank=True, default=0, null=True)),
                ('punches', models.IntegerField(blank=True, default=0, null=True)),
                ('high_claims', models.IntegerField(blank=True, default=0, null=True)),
                ('catches', models.IntegerField(blank=True, default=0, null=True)),
                ('sweeper_clearance', models.IntegerField(blank=True, default=0, null=True)),
                ('throw_outs', models.IntegerField(blank=True, default=0, null=True)),
                ('goal_kicks', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerinfo')),
            ],
        ),
    ]
