# Generated by Django 3.1.7 on 2021-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210329_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='goal_kicks',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
