# Generated by Django 3.1.7 on 2021-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210330_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensivestats',
            name='clearances',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='defensivestats',
            name='headed_clearances',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinarystats',
            name='offsides',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='chances_created',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='cross_accuracy',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='crosses',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='long_balls',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='passes_per_match',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='through_balls',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='total_passes',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
