# Generated by Django 3.1.7 on 2021-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210330_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensivestats',
            name='headed_clearances',
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='tacles_success_rate',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
