# Generated by Django 3.1.7 on 2021-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210330_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackingstats',
            name='freekicks',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='goals',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='headers',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='hit_woodwork',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='left_foot_goals',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='penalties',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='right_foot_goals',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='shots',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='shots_on_target',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
