# Generated by Django 3.1.7 on 2021-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210330_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackingstats',
            name='freekicks',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='goals',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='headers',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='hit_woodwork',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='left_foot_goals',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='penalties',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='right_foot_goals',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='shots',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackingstats',
            name='shots_on_target',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='aerial_battles_lost',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='aerial_battles_won',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='blocked_shots',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='clean_sheets',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='clearances',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='duels_won',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='dues_lost',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='goals_conceded',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='interceptions',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='own_goals',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='recoveries',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='successful_50_50',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='tackles',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='tacles_success_rate',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinarystats',
            name='fouls',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinarystats',
            name='offsides',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinarystats',
            name='red_cards',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='disciplinarystats',
            name='yellow_cards',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='catches',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='clean_sheets',
            field=models.IntegerField(blank=True, default='Not Available', null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='goal_kicks',
            field=models.CharField(blank=True, default='Not Available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='high_claims',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='penalties_saved',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='punches',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='saves',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='sweeper_clearance',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='throw_outs',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='assists',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='chances_created',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='cross_accuracy',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='crosses',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='long_balls',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='passes_per_match',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='through_balls',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamplaystats',
            name='total_passes',
            field=models.CharField(blank=True, default='Not Available', max_length=20, null=True),
        ),
    ]
